appname = api_mid_AgroCampo
httpport = 8080
runmode = dev

///leer json
copyrequestbody = true

///datos de la base de postgresSQL
pg_host =localhost
pg_puerto =5432
pg_usuario = postgres
pg_clave=postgres
pg_base_de_datos=Agrocampo